version: '3.8'

services:
  # ── Backend Público ──────────────────────────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: publico-vuelos-backend
    restart: unless-stopped
    environment:
      PORT: 3000
      # LOCAL: Usa la IP de tu máquina 
      # AWS: Usa la IP Privada de la instancia EC2Priv
      MONGO_URI: mongodb://host.docker.internal:27017/vuelos
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - vuelos-net

  # ── Frontend Público ─────────────────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: publico-vuelos-frontend
    restart: unless-stopped
    environment:
      # Muy importante: El front necesita saber dónde está el API
      REACT_APP_API_URL: http://<IP_PUBLICA_O_LOCAL>:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - vuelos-net

networks:
  vuelos-net:
    driver: bridge